"""improve must patch last-run DEGRADED pages in place, not mint a sibling wiki."""

from __future__ import annotations

import json
from pathlib import Path

import pytest
from typer.testing import CliRunner

from repo_wiki.cli import app
from repo_wiki.core.config import RepoWikiConfig
from repo_wiki.llm.config import LLMProviderConfig
from repo_wiki.llm.models import ChatRequest, ChatResponse, LLMProvider, ProviderCapabilities
from repo_wiki.orchestration.eval_layout import EvalOutputProfile
from repo_wiki.orchestration.service import RepoWikiService

runner = CliRunner()

ORIGINAL_MARKDOWN = """# Sample Page

## 简介

This page was generated by the first handbook pass and must stay intact for
PASS pages. It includes enough prose so the composer keeps the page.

## 项目结构

The repository layout is described here with extra padding sentences so
validation passes without falling back to templates during the success path.
"""

IMPROVED_MARKDOWN = """# Sample Page

## 简介

IMPROVED_DEGRADED_PAGE this rewrite is the in-place recovery body for
priority pages. It includes enough prose so the composer keeps the page.

## 项目结构

The recovered chapter still describes layout with extra padding sentences so
validation passes without falling back to templates during the success path.
"""

PASS_STAMP = "PASS_PAGE_MUST_STAY_INTACT"
DEGRADED_STAMP = "OLD_DEGRADED_CONTENT_MUST_BE_REPLACED"


class _ScriptedProvider(LLMProvider):
    def __init__(self, markdown: str) -> None:
        self._markdown = markdown
        self._call_count = 0
        self._config = LLMProviderConfig(
            provider="mock",
            model="mock-gpt",
            timeout=2.0,
            max_retries=0,
        )

    @property
    def name(self) -> str:
        return "in-place-fake"

    @property
    def capabilities(self) -> ProviderCapabilities:
        return ProviderCapabilities()

    @property
    def call_count(self) -> int:
        return self._call_count

    async def chat(self, request: ChatRequest) -> ChatResponse:
        self._call_count += 1
        return ChatResponse(content=self._markdown, model="mock-gpt")

    def validate_config(self) -> list[tuple[str, str | None, str]]:
        return []


def _write_small_repo(root: Path) -> None:
    (root / "src").mkdir(parents=True)
    (root / "src" / "app.py").write_text(
        """
from fastapi import FastAPI

app = FastAPI()

@app.get('/health')
def health():
    return {'status': 'ok'}
""".strip()
        + "\n",
        encoding="utf-8",
    )
    (root / "README.md").write_text(
        "# Sample Service\n\nSmall FastAPI service.\n", encoding="utf-8"
    )
    (root / "repo-wiki.yaml").write_text(
        "\n".join(
            [
                "project:",
                "  name: sample",
                f"  root: {root}",
                "  exclude:",
                "    - .repo-agent-eval/**",
                "llm:",
                "  force_mock_llm: false",
            ]
        )
        + "\n",
        encoding="utf-8",
    )


def _service(root: Path) -> RepoWikiService:
    cfg = RepoWikiConfig.model_validate(
        {
            "project": {
                "name": "sample",
                "root": str(root),
                "exclude": [".repo-agent-eval/**"],
            },
            "qoder_like": {"min_pages": 3, "max_pages": 3},
            "llm": {"force_mock_llm": False, "timeout": 2.0, "max_retries": 0},
        }
    )
    return RepoWikiService(cfg)


def _install_provider(monkeypatch: pytest.MonkeyPatch, provider: _ScriptedProvider) -> None:
    config = provider._config

    def _resolve(self: RepoWikiService) -> tuple[object, LLMProviderConfig, dict[str, object]]:
        return (
            provider,
            config,
            {
                "effective_provider": provider.name,
                "model": config.model,
                "mode": "real",
                "mock_reason": None,
                "fallback_warning": None,
            },
        )

    monkeypatch.setattr(RepoWikiService, "_resolve_qoder_like_llm", _resolve)


def _content_md_map(content_dir: Path) -> dict[str, str]:
    return {
        path.relative_to(content_dir).as_posix(): path.read_text(encoding="utf-8")
        for path in sorted(content_dir.rglob("*.md"))
        if path.is_file()
    }


def _sibling_timestamp_runs(eval_root: Path, last_run_name: str) -> list[str]:
    names: list[str] = []
    for entry in eval_root.iterdir():
        if entry.is_dir() and entry.name.startswith("run-") and entry.name != last_run_name:
            names.append(entry.name)
    runs_bucket = eval_root / "runs"
    if runs_bucket.is_dir():
        for entry in runs_bucket.iterdir():
            if entry.is_dir() and entry.name.startswith("run-") and entry.name != last_run_name:
                names.append(f"runs/{entry.name}")
    return names


def test_improve_defaults_run_id_to_last_handbook(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """Without --run-id, improve must reuse select_run, not mint run-{ts}."""
    eval_root = tmp_path / ".repo-agent-eval"
    run_dir = eval_root / "handbook-2026-08-23a"
    meta = run_dir / "repowiki" / "zh" / "meta"
    meta.mkdir(parents=True)
    (run_dir / "manifest.json").write_text(
        json.dumps({"run_id": "handbook-2026-08-23a"}), encoding="utf-8"
    )
    (meta / "quality-report.json").write_text(
        json.dumps(
            {
                "page_quality": [
                    {"page_id": "quick-start", "quality_state": "DEGRADED"},
                    {"page_id": "overview", "quality_state": "PASS"},
                    {"page_id": "installation", "quality_state": "DEGRADED"},
                ]
            }
        ),
        encoding="utf-8",
    )

    captured: dict[str, object] = {}

    def fake_generate(
        self: RepoWikiService,
        eval_profile: EvalOutputProfile | None = None,
        run_id: str | None = None,
        in_place: bool = False,
    ) -> dict[str, object]:
        assert eval_profile is not None
        captured["run_id"] = run_id
        captured["in_place"] = in_place
        captured["profile_root"] = str(Path(eval_profile.root).resolve())
        captured["run_dir"] = str(eval_profile.get_run_dir(run_id).resolve())
        captured["priority_ids"] = __import__("os").environ.get("REPO_WIKI_LLM_PRIORITY_PAGE_IDS")
        return {"manifest_path": str(run_dir / "manifest.json")}

    monkeypatch.setattr(RepoWikiService, "generate", fake_generate)
    monkeypatch.chdir(tmp_path)

    result = runner.invoke(
        app,
        ["improve", "--profile", "qoder-like", "--output", str(eval_root), "--real-max-calls", "2"],
    )
    assert result.exit_code == 0, result.stdout + result.stderr
    assert captured["run_id"] == "handbook-2026-08-23a"
    assert captured["in_place"] is True
    assert captured["run_dir"] == str(run_dir.resolve())
    assert captured["priority_ids"] == "quick-start,installation"
    assert not str(captured["run_id"]).startswith("run-")


def test_improve_patches_last_handbook_in_place_for_degraded_pages(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """Two last-run DEGRADED Chinese pages re-compose; PASS page and run dir stay."""
    repo = tmp_path / "repo"
    repo.mkdir()
    _write_small_repo(repo)
    eval_root = repo / ".repo-agent-eval"
    last_run_id = "handbook-2026-08-23a"

    monkeypatch.setenv("REPO_WIKI_LLM_PAGE_LIMIT", "3")
    monkeypatch.setenv("REPO_WIKI_QODER_LIKE_MIN_PAGES", "3")
    monkeypatch.setenv("REPO_WIKI_QODER_LIKE_MAX_PAGES", "3")
    monkeypatch.setenv("REPO_WIKI_LLM_PRIORITY", "plan")
    monkeypatch.setenv("REPO_WIKI_COMPACT_LLM_PROMPT", "1")
    monkeypatch.setenv(
        "REPO_WIKI_COMPOSER_CACHE_PATH",
        str(eval_root / ".runtime" / "composer_cache.sqlite3"),
    )

    first = _ScriptedProvider(ORIGINAL_MARKDOWN)
    _install_provider(monkeypatch, first)
    profile = EvalOutputProfile(
        name="qoder-like",
        root=str(eval_root),
        create_subdirs=True,
        content_subdir="repowiki/zh/content",
    )
    first_result = _service(repo).generate(eval_profile=profile, run_id=last_run_id)
    assert first.call_count == 3
    run_dir = Path(str(first_result["manifest_path"])).parent
    assert run_dir.name == last_run_id
    content_dir = run_dir / "repowiki" / "zh" / "content"
    quality_path = run_dir / "repowiki" / "zh" / "meta" / "quality-report.json"
    quality = json.loads(quality_path.read_text(encoding="utf-8"))
    pages = list(quality.get("page_quality") or [])
    assert len(pages) >= 3
    degraded_ids = [str(pages[0]["page_id"]), str(pages[1]["page_id"])]
    pass_id = str(pages[2]["page_id"])
    path_by_id = {str(item["page_id"]): str(item["relative_path"]) for item in pages}

    for page_id in degraded_ids:
        relative = path_by_id[page_id]
        assert not relative.startswith("docs/")
        assert any(ord(char) > 127 for char in relative)
        target = content_dir / relative
        target.write_text(
            target.read_text(encoding="utf-8") + f"\n{DEGRADED_STAMP}\n", encoding="utf-8"
        )
    pass_relative = path_by_id[pass_id]
    pass_file = content_dir / pass_relative
    pass_file.write_text(
        pass_file.read_text(encoding="utf-8") + f"\n{PASS_STAMP}\n", encoding="utf-8"
    )

    quality["page_quality"][0]["quality_state"] = "DEGRADED"
    quality["page_quality"][1]["quality_state"] = "DEGRADED"
    quality["page_quality"][2]["quality_state"] = "PASS"
    quality_path.write_text(json.dumps(quality, ensure_ascii=False, indent=2), encoding="utf-8")

    before = _content_md_map(content_dir)
    second = _ScriptedProvider(IMPROVED_MARKDOWN)
    _install_provider(monkeypatch, second)
    monkeypatch.chdir(repo)

    result = runner.invoke(
        app,
        [
            "improve",
            "--profile",
            "qoder-like",
            "--output",
            str(eval_root),
            "--config",
            str(repo / "repo-wiki.yaml"),
            "--real-max-calls",
            "2",
            "--max-pages",
            "3",
            "--priority",
            "plan",
        ],
    )
    assert result.exit_code == 0, result.stdout + result.stderr
    assert second.call_count == 2
    assert not _sibling_timestamp_runs(eval_root, last_run_id)
    assert run_dir.is_dir()
    assert (eval_root / last_run_id).resolve() == run_dir.resolve()

    after = _content_md_map(content_dir)
    assert set(after) == set(before)
    changed = [path for path, body in after.items() if body != before[path]]
    expected = {path_by_id[page_id] for page_id in degraded_ids}
    assert set(changed) == expected
    for relative in expected:
        assert DEGRADED_STAMP not in after[relative]
        assert "IMPROVED_DEGRADED_PAGE" in after[relative]
        assert "本页暂" not in after[relative]
    assert PASS_STAMP in after[pass_relative]
    assert "IMPROVED_DEGRADED_PAGE" not in after[pass_relative]
    assert after[pass_relative] == before[pass_relative]
