"""Circuit-break must stop new LLM page calls without waiting page timeouts.

Round 3 (FastAPI RealWorld, CLI a3d58b4): 16×529 then
``provider_disabled_after_failures=true``, but all 89 compose jobs were
submitted to ``asyncio.gather`` first, so remaining pages could not skip
LLM and became extra fallbacks (2 → 26). Empty-content retry (#42) and
HTTP 5xx/429 retry (#40) stay covered in ``test_llm_compose_retry.py``.
"""

from __future__ import annotations

import asyncio
import time
from pathlib import Path

import pytest

from repo_wiki.core.config import RepoWikiConfig
from repo_wiki.core.contracts import RepositoryInfo, RepositorySnapshot
from repo_wiki.llm.config import LLMProviderConfig
from repo_wiki.llm.models import (
    ChatRequest,
    ChatResponse,
    ErrorCode,
    LLMProvider,
    ProviderCapabilities,
    RetryableError,
)
from repo_wiki.orchestration.service import RepoWikiService
from repo_wiki.planner.schema import WikiPagePlan, WikiPlanManifest, WikiTaxonomyCategory

PAGE_COUNT = 8
MAX_FAILURES = 2
CONCURRENCY = 2
PAGE_TIMEOUT_SECONDS = 1.5
SUCCESS_MARKDOWN = """# Sample Page

## 简介

This page was generated by a fake provider for circuit-break scheduler tests.
It includes enough prose so the composer keeps the page instead of rejecting
it for insufficient content. Healthy providers must still compose every page.

## 项目结构

The repository layout is described here with extra padding sentences so
validation passes without falling back to templates during the success path.
"""

# HTTP 200 + non-empty tokens, but almost no counted prose (headers / fences /
# list items are stripped). Composer must reject this as insufficient prose.
INSUFFICIENT_PROSE_MARKDOWN = """# Sample Page

```python
def pad_out_the_body():
    return "x" * 80
value_a = 1
value_b = 2
value_c = 3
value_d = 4
value_e = 5
```

- bullet one with extra words for length
- bullet two with extra words for length
- bullet three with extra words for length
"""

ENOUGH_TOKENS = {
    "prompt_tokens": 240,
    "completion_tokens": 360,
    "total_tokens": 600,
}


def _retryable_529() -> RetryableError:
    return RetryableError(
        message="Server error: 529",
        code=ErrorCode.SERVER_ERROR,
        details={"status": 529},
    )


def _success_response() -> ChatResponse:
    return ChatResponse(content=SUCCESS_MARKDOWN, model="mock-gpt")


class CircuitBreak529Provider(LLMProvider):
    """Immediate 529 for a budget of calls, then hang (cancelled by page timeout).

    Fail-fast calls wait until ``fail_fast_limit`` chats are in flight so the
    scheduler race (admit a third job before the second failure is recorded)
    is deterministic under pytest-asyncio.
    """

    def __init__(self, fail_fast_limit: int) -> None:
        self._fail_fast_limit = fail_fast_limit
        self._call_count = 0
        self._hang_count = 0
        self._fail_fast_started = 0
        self._fail_fast_gate = asyncio.Event()
        self._config = LLMProviderConfig(
            provider="mock",
            model="mock-gpt",
            timeout=PAGE_TIMEOUT_SECONDS,
            max_retries=0,
        )

    @property
    def name(self) -> str:
        return "circuit-break-529-fake"

    @property
    def capabilities(self) -> ProviderCapabilities:
        return ProviderCapabilities()

    @property
    def call_count(self) -> int:
        return self._call_count

    @property
    def hang_count(self) -> int:
        return self._hang_count

    async def chat(self, request: ChatRequest) -> ChatResponse:
        self._call_count += 1
        if self._call_count <= self._fail_fast_limit:
            self._fail_fast_started += 1
            if self._fail_fast_started >= self._fail_fast_limit:
                self._fail_fast_gate.set()
            await self._fail_fast_gate.wait()
            raise _retryable_529()
        self._hang_count += 1
        await request_never_returns()
        raise AssertionError("hang path must be cancelled, not return")

    def validate_config(self) -> list[tuple[str, str | None, str]]:
        return []


class HealthyLLMProvider(LLMProvider):
    """Always returns composable Markdown; never hangs or 529s."""

    def __init__(self) -> None:
        self._call_count = 0
        self._config = LLMProviderConfig(
            provider="mock",
            model="mock-gpt",
            timeout=PAGE_TIMEOUT_SECONDS,
            max_retries=0,
        )

    @property
    def name(self) -> str:
        return "healthy-fake"

    @property
    def capabilities(self) -> ProviderCapabilities:
        return ProviderCapabilities()

    @property
    def call_count(self) -> int:
        return self._call_count

    async def chat(self, request: ChatRequest) -> ChatResponse:
        self._call_count += 1
        return _success_response()

    def validate_config(self) -> list[tuple[str, str | None, str]]:
        return []


class InsufficientProseThenHealthyProvider(LLMProvider):
    """First N chats are HTTP 200 + tokens but fail the prose-density check."""

    def __init__(self, reject_count: int) -> None:
        self._reject_count = reject_count
        self._call_count = 0
        self._config = LLMProviderConfig(
            provider="mock",
            model="mock-gpt",
            timeout=PAGE_TIMEOUT_SECONDS,
            max_retries=0,
        )

    @property
    def name(self) -> str:
        return "insufficient-prose-fake"

    @property
    def capabilities(self) -> ProviderCapabilities:
        return ProviderCapabilities()

    @property
    def call_count(self) -> int:
        return self._call_count

    async def chat(self, request: ChatRequest) -> ChatResponse:
        self._call_count += 1
        if self._call_count <= self._reject_count:
            return ChatResponse(
                content=INSUFFICIENT_PROSE_MARKDOWN,
                model="mock-gpt",
                usage=dict(ENOUGH_TOKENS),
            )
        return _success_response()

    def validate_config(self) -> list[tuple[str, str | None, str]]:
        return []


class Always529Provider(LLMProvider):
    """Immediate 529 on every chat — a real provider-outage signal."""

    def __init__(self) -> None:
        self._call_count = 0
        self._config = LLMProviderConfig(
            provider="mock",
            model="mock-gpt",
            timeout=PAGE_TIMEOUT_SECONDS,
            max_retries=0,
        )

    @property
    def name(self) -> str:
        return "always-529-fake"

    @property
    def capabilities(self) -> ProviderCapabilities:
        return ProviderCapabilities()

    @property
    def call_count(self) -> int:
        return self._call_count

    async def chat(self, request: ChatRequest) -> ChatResponse:
        self._call_count += 1
        raise _retryable_529()

    def validate_config(self) -> list[tuple[str, str | None, str]]:
        return []


class AlwaysEmptyContentProvider(LLMProvider):
    """HTTP 200 with empty assistant content — a real provider-outage signal."""

    def __init__(self) -> None:
        self._call_count = 0
        self._config = LLMProviderConfig(
            provider="mock",
            model="mock-gpt",
            timeout=PAGE_TIMEOUT_SECONDS,
            max_retries=0,
        )

    @property
    def name(self) -> str:
        return "empty-content-fake"

    @property
    def capabilities(self) -> ProviderCapabilities:
        return ProviderCapabilities()

    @property
    def call_count(self) -> int:
        return self._call_count

    async def chat(self, request: ChatRequest) -> ChatResponse:
        self._call_count += 1
        return ChatResponse(content="", model="mock-gpt")

    def validate_config(self) -> list[tuple[str, str | None, str]]:
        return []


class AlwaysTimeoutProvider(LLMProvider):
    """Hang until the page wait_for timeout — a real provider-outage signal."""

    def __init__(self) -> None:
        self._call_count = 0
        self._config = LLMProviderConfig(
            provider="mock",
            model="mock-gpt",
            timeout=PAGE_TIMEOUT_SECONDS,
            max_retries=0,
        )

    @property
    def name(self) -> str:
        return "timeout-fake"

    @property
    def capabilities(self) -> ProviderCapabilities:
        return ProviderCapabilities()

    @property
    def call_count(self) -> int:
        return self._call_count

    async def chat(self, request: ChatRequest) -> ChatResponse:
        self._call_count += 1
        await request_never_returns()
        raise AssertionError("timeout path must be cancelled, not return")

    def validate_config(self) -> list[tuple[str, str | None, str]]:
        return []


class Single529ThenHealthyProvider(LLMProvider):
    """First chat is 529; later chats succeed. Must not trip the failure budget."""

    def __init__(self) -> None:
        self._call_count = 0
        self._config = LLMProviderConfig(
            provider="mock",
            model="mock-gpt",
            timeout=PAGE_TIMEOUT_SECONDS,
            max_retries=0,
        )

    @property
    def name(self) -> str:
        return "single-529-fake"

    @property
    def capabilities(self) -> ProviderCapabilities:
        return ProviderCapabilities()

    @property
    def call_count(self) -> int:
        return self._call_count

    async def chat(self, request: ChatRequest) -> ChatResponse:
        self._call_count += 1
        if self._call_count == 1:
            raise _retryable_529()
        return _success_response()

    def validate_config(self) -> list[tuple[str, str | None, str]]:
        return []


async def request_never_returns() -> None:
    """Park until the page ``wait_for`` timeout cancels the task."""
    await asyncio.Event().wait()


def _plan(n: int = PAGE_COUNT) -> WikiPlanManifest:
    pages = [
        WikiPagePlan(
            page_id=f"page-{idx:02d}",
            title=f"Sample Page {idx:02d}",
            category=WikiTaxonomyCategory.PROJECT_OVERVIEW,
            output_path=f"docs/page-{idx:02d}.md",
        )
        for idx in range(n)
    ]
    return WikiPlanManifest(pages=pages)


def _snapshot(root: Path) -> RepositorySnapshot:
    return RepositorySnapshot(
        repository=RepositoryInfo(
            name="circuit-break-test",
            root_path=str(root),
            language="python",
            framework="pytest",
        )
    )


def _service(root: Path) -> RepoWikiService:
    config = RepoWikiConfig.model_validate(
        {
            "project": {"name": "circuit-break-test", "root": str(root)},
            "llm": {
                "force_mock_llm": True,
                "max_concurrent": CONCURRENCY,
                "timeout": PAGE_TIMEOUT_SECONDS,
                "max_retries": 0,
            },
        }
    )
    return RepoWikiService(config)


def _summary(provider: LLMProvider, config: LLMProviderConfig) -> dict[str, object]:
    return {
        "effective_provider": provider.name,
        "model": config.model,
        "mode": "real",
        "mock_reason": None,
        "fallback_warning": None,
    }


def _install_provider(
    monkeypatch: pytest.MonkeyPatch,
    service: RepoWikiService,
    provider: LLMProvider,
) -> LLMProviderConfig:
    config = provider._config  # type: ignore[attr-defined]
    monkeypatch.setattr(
        service,
        "_resolve_qoder_like_llm",
        lambda: (provider, config, _summary(provider, config)),
    )
    return config


@pytest.fixture
def compose_env(monkeypatch: pytest.MonkeyPatch, tmp_path: Path) -> Path:
    monkeypatch.setenv("REPO_WIKI_LLM_MAX_FAILURES", str(MAX_FAILURES))
    monkeypatch.setenv("REPO_WIKI_LLM_CONCURRENCY", str(CONCURRENCY))
    monkeypatch.setenv("REPO_WIKI_LLM_PAGE_TIMEOUT_SECONDS", str(PAGE_TIMEOUT_SECONDS))
    monkeypatch.setenv("REPO_WIKI_LLM_PRIORITY", "plan")
    monkeypatch.setenv(
        "REPO_WIKI_COMPOSER_CACHE_PATH",
        str(tmp_path / "composer-cache.sqlite3"),
    )

    async def _instant(_delay: float) -> None:
        return None

    monkeypatch.setattr("repo_wiki.llm.retry.asyncio.sleep", _instant)
    return tmp_path


@pytest.mark.asyncio
async def test_circuit_break_skips_remaining_pages_without_timeout_wait(
    compose_env: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    root = compose_env / "repo"
    root.mkdir()
    output_dir = compose_env / "run"
    output_dir.mkdir()
    provider = CircuitBreak529Provider(fail_fast_limit=MAX_FAILURES)
    service = _service(root)
    _install_provider(monkeypatch, service, provider)

    started = time.perf_counter()
    result = await service._compose_qoder_like_pages(
        plan=_plan(),
        evidence_bindings={},
        snapshot=_snapshot(root),
        output_dir=output_dir,
    )
    elapsed = time.perf_counter() - started
    llm = result["llm"]

    # Scheduling test, not a micro-benchmark. CI 3.11 observed 1.53s vs a
    # 1.5s cap. The pre-fix gather queued every leftover page, so remaining
    # work waited ceil((8-2)/2) timeout waves (~4.5s). 3s is above one
    # timeout of jitter and still below that gather wait. hang_count==0 is
    # the proof leftover pages never entered the per-page timeout path.
    assert elapsed < 3.0
    assert provider.hang_count == 0
    assert provider.call_count == MAX_FAILURES
    assert provider.call_count < PAGE_COUNT
    assert llm["provider_disabled_after_failures"] is True
    assert llm["fallback_page_count"] == PAGE_COUNT
    assert llm["llm_call_count"] == provider.call_count
    assert llm["llm_call_count"] < PAGE_COUNT
    fallback_modes = {meta["generation_mode"] for meta in result["page_metadata"]}
    assert fallback_modes == {"fallback"}
    disabled_reasons = [
        reason
        for meta in result["page_metadata"]
        for reason in meta["reasons"]
        if "provider disabled after" in reason
    ]
    assert disabled_reasons


@pytest.mark.asyncio
async def test_healthy_provider_composes_all_pages(
    compose_env: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    root = compose_env / "repo"
    root.mkdir()
    output_dir = compose_env / "run"
    output_dir.mkdir()
    provider = HealthyLLMProvider()
    service = _service(root)
    _install_provider(monkeypatch, service, provider)

    result = await service._compose_qoder_like_pages(
        plan=_plan(),
        evidence_bindings={},
        snapshot=_snapshot(root),
        output_dir=output_dir,
    )
    llm = result["llm"]

    assert provider.call_count == PAGE_COUNT
    assert llm["llm_call_count"] == PAGE_COUNT
    assert llm["fallback_page_count"] == 0
    assert llm["provider_disabled_after_failures"] is False
    assert {meta["generation_mode"] for meta in result["page_metadata"]} == {"llm"}
    assert len(result["pages"]) == PAGE_COUNT
    assert all(markdown for _path, markdown in result["pages"])


@pytest.mark.asyncio
async def test_single_529_does_not_disable_provider(
    compose_env: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    root = compose_env / "repo"
    root.mkdir()
    output_dir = compose_env / "run"
    output_dir.mkdir()
    provider = Single529ThenHealthyProvider()
    service = _service(root)
    _install_provider(monkeypatch, service, provider)

    result = await service._compose_qoder_like_pages(
        plan=_plan(),
        evidence_bindings={},
        snapshot=_snapshot(root),
        output_dir=output_dir,
    )
    llm = result["llm"]
    modes = [meta["generation_mode"] for meta in result["page_metadata"]]

    assert llm["provider_disabled_after_failures"] is False
    assert llm["fallback_page_count"] == 1
    assert modes.count("fallback") == 1
    assert modes.count("llm") == PAGE_COUNT - 1
    assert provider.call_count == PAGE_COUNT


@pytest.mark.asyncio
async def test_insufficient_prose_rejects_do_not_trip_circuit_breaker(
    compose_env: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """R10: 3× Insufficient prose (HTTP 200 + tokens) must not disable the provider."""
    monkeypatch.setenv("REPO_WIKI_LLM_MAX_FAILURES", "3")
    root = compose_env / "repo"
    root.mkdir()
    output_dir = compose_env / "run"
    output_dir.mkdir()
    provider = InsufficientProseThenHealthyProvider(reject_count=3)
    service = _service(root)
    _install_provider(monkeypatch, service, provider)

    result = await service._compose_qoder_like_pages(
        plan=_plan(),
        evidence_bindings={},
        snapshot=_snapshot(root),
        output_dir=output_dir,
    )
    llm = result["llm"]
    modes = [meta["generation_mode"] for meta in result["page_metadata"]]
    prose_rejects = [
        reason
        for meta in result["page_metadata"]
        for reason in meta["reasons"]
        if "Insufficient prose" in reason
    ]
    disabled_reasons = [
        reason
        for meta in result["page_metadata"]
        for reason in meta["reasons"]
        if "provider disabled after" in reason
    ]

    assert llm["max_provider_failures"] == 3
    assert llm["provider_disabled_after_failures"] is False
    assert provider.call_count == PAGE_COUNT
    assert llm["llm_call_count"] == PAGE_COUNT
    assert llm["fallback_page_count"] == 3
    assert len(prose_rejects) == 3
    assert not disabled_reasons
    assert modes.count("fallback") == 3
    assert modes.count("llm") == PAGE_COUNT - 3


@pytest.mark.asyncio
async def test_three_consecutive_529s_still_trip_circuit_breaker(
    compose_env: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """#49: three real provider 529s still consume the failure budget."""
    monkeypatch.setenv("REPO_WIKI_LLM_MAX_FAILURES", "3")
    root = compose_env / "repo"
    root.mkdir()
    output_dir = compose_env / "run"
    output_dir.mkdir()
    provider = Always529Provider()
    service = _service(root)
    _install_provider(monkeypatch, service, provider)

    result = await service._compose_qoder_like_pages(
        plan=_plan(),
        evidence_bindings={},
        snapshot=_snapshot(root),
        output_dir=output_dir,
    )
    llm = result["llm"]

    assert llm["max_provider_failures"] == 3
    assert llm["provider_disabled_after_failures"] is True
    assert provider.call_count == 3
    assert provider.call_count < PAGE_COUNT
    assert llm["llm_call_count"] < PAGE_COUNT
    assert llm["fallback_page_count"] == PAGE_COUNT
    disabled_reasons = [
        reason
        for meta in result["page_metadata"]
        for reason in meta["reasons"]
        if "provider disabled after" in reason
    ]
    assert disabled_reasons


@pytest.mark.asyncio
async def test_three_consecutive_empty_content_failures_still_trip_circuit_breaker(
    compose_env: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """#49: three empty-content provider failures still disable later LLM calls."""
    monkeypatch.setenv("REPO_WIKI_LLM_MAX_FAILURES", "3")
    root = compose_env / "repo"
    root.mkdir()
    output_dir = compose_env / "run"
    output_dir.mkdir()
    provider = AlwaysEmptyContentProvider()
    service = _service(root)
    _install_provider(monkeypatch, service, provider)

    result = await service._compose_qoder_like_pages(
        plan=_plan(),
        evidence_bindings={},
        snapshot=_snapshot(root),
        output_dir=output_dir,
    )
    llm = result["llm"]

    assert llm["max_provider_failures"] == 3
    assert llm["provider_disabled_after_failures"] is True
    assert provider.call_count == 3
    assert provider.call_count < PAGE_COUNT
    assert llm["fallback_page_count"] == PAGE_COUNT
    disabled_reasons = [
        reason
        for meta in result["page_metadata"]
        for reason in meta["reasons"]
        if "provider disabled after" in reason
    ]
    assert disabled_reasons


@pytest.mark.asyncio
async def test_three_consecutive_timeouts_still_trip_circuit_breaker(
    compose_env: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """#49: three page timeouts still disable later LLM calls."""
    monkeypatch.setenv("REPO_WIKI_LLM_MAX_FAILURES", "3")
    root = compose_env / "repo"
    root.mkdir()
    output_dir = compose_env / "run"
    output_dir.mkdir()
    provider = AlwaysTimeoutProvider()
    service = _service(root)
    _install_provider(monkeypatch, service, provider)

    result = await service._compose_qoder_like_pages(
        plan=_plan(),
        evidence_bindings={},
        snapshot=_snapshot(root),
        output_dir=output_dir,
    )
    llm = result["llm"]

    assert llm["max_provider_failures"] == 3
    assert llm["provider_disabled_after_failures"] is True
    assert provider.call_count == 3
    assert provider.call_count < PAGE_COUNT
    assert llm["fallback_page_count"] == PAGE_COUNT
    disabled_reasons = [
        reason
        for meta in result["page_metadata"]
        for reason in meta["reasons"]
        if "provider disabled after" in reason
    ]
    assert disabled_reasons
