"""Qoder-like isolated generation: resolve mock vs real LLM consistently.

The composer stack is shared between mock and real providers; this module centralizes
when we attach :class:`MockLLMProvider` vs :func:`create_provider_from_config` so that:

- Real HTTP providers (Minimax, OpenAI-compatible, custom ``base_url``) are used whenever
  the resolved API key env var is set and mock is not forced.
- CI/tests can force mock via env or YAML without silent surprises.
"""

from __future__ import annotations

import os
from typing import Any

from repo_wiki.core.logging import info as log_info
from repo_wiki.core.logging import warn as log_warn
from repo_wiki.llm.config import LLMProviderConfig, get_api_key_from_env, resolve_llm_config
from repo_wiki.llm.diagnostics import create_provider_from_config
from repo_wiki.llm.providers import create_mock_provider

ENV_FORCE_MOCK_LLM = "REPO_WIKI_FORCE_MOCK_LLM"


def env_force_mock_llm() -> bool:
    """True when ``REPO_WIKI_FORCE_MOCK_LLM`` is set to a truthy value."""
    v = os.environ.get(ENV_FORCE_MOCK_LLM, "").strip().lower()
    return v in ("1", "true", "yes", "on")


def resolve_qoder_like_llm(
    *,
    llm_config_dict: dict[str, Any],
    force_mock_llm_config: bool = False,
) -> tuple[Any, LLMProviderConfig, dict[str, Any]]:
    """Pick mock or real provider for qoder-like ``RepoWikiService._generate_isolated_eval``.

    **Real path:** ``get_api_key_from_env`` for the resolved ``api_key_env`` returns a value,
    and neither env nor config forces mock. Then ``create_provider_from_config`` is used
    (Minimax → :class:`MinimaxProvider`; anything else → :class:`OpenAICompatibleProvider` with
    ``base_url`` for OpenAI-compatible / proxy endpoints).

    **Mock path:** No API key, or mock forced. Returns :func:`create_mock_provider` with a
    stable synthetic body so token/cost estimates stay deterministic and logs explain why.

    Args:
        llm_config_dict: Raw ``llm`` section (e.g. ``RepoWikiConfig.llm.model_dump()``).
        force_mock_llm_config: When True, always mock (from ``llm.force_mock_llm`` in YAML).

    Returns:
        ``(provider, effective_config, summary_dict)``. Summary includes ``mode``,
        ``mock_reason`` (``forced_env`` | ``forced_config`` | ``missing_api_key`` | ``None``),
        and ``fallback_warning`` text when mock was not explicitly forced.
    """
    llm_config, warnings = resolve_llm_config(config=llm_config_dict)
    api_key_present = bool(get_api_key_from_env(llm_config.api_key_env))

    force_mock = env_force_mock_llm() or force_mock_llm_config
    mock_reason: str | None = None
    if env_force_mock_llm():
        mock_reason = "forced_env"
    elif force_mock_llm_config:
        mock_reason = "forced_config"

    summary_base: dict[str, Any] = {
        "requested_provider": llm_config.provider,
        "requested_model": llm_config.model,
        "api_key_env": llm_config.api_key_env,
        "api_key_present": api_key_present,
        "config_warnings": [reason.value for reason, _ in warnings],
        "force_mock_env": env_force_mock_llm(),
        "force_mock_config": force_mock_llm_config,
    }

    def _mock_bundle(reason: str | None) -> tuple[Any, LLMProviderConfig, dict[str, Any]]:
        effective = LLMProviderConfig(
            provider="mock",
            model="mock-gpt",
            max_tokens=llm_config.max_tokens,
            temperature=llm_config.temperature,
            timeout=llm_config.timeout,
            max_retries=llm_config.max_retries,
        )
        provider = create_mock_provider(
            effective,
            response_content=(
                "This page was generated by the LLMPageComposer mock provider for CI. "
                "It uses the same page-plan, evidence, prompt, and composer path as real providers."
            ),
        )
        fallback_warning = None
        if reason in ("forced_env", "forced_config"):
            log_info(
                f"Qoder-like LLM: using MOCK (reason={reason}). "
                f"Unset {ENV_FORCE_MOCK_LLM} / llm.force_mock_llm to allow real providers when an API key is set."
            )
        elif reason == "missing_api_key":
            fallback_warning = (
                f"Qoder-like generation is using the MOCK LLM: no API key in {llm_config.api_key_env}. "
                f"Set that env var (or llm.api_key_env in repo-wiki.yaml) to use provider '{llm_config.provider}'. "
                "Mock runs use synthetic token/latency estimates and are not comparable to real LLM pilots."
            )
            log_warn(fallback_warning)
        out = {
            **summary_base,
            "effective_provider": getattr(provider, "name", effective.provider),
            "model": effective.model,
            "mode": "mock",
            "mock_reason": reason,
            "fallback_warning": fallback_warning,
        }
        return provider, effective, out

    if force_mock:
        return _mock_bundle(mock_reason)

    if api_key_present:
        provider = create_provider_from_config(llm_config)
        summary = {
            **summary_base,
            "effective_provider": getattr(provider, "name", llm_config.provider),
            "model": llm_config.model,
            "mode": "real",
            "mock_reason": None,
            "fallback_warning": None,
        }
        return provider, llm_config, summary

    return _mock_bundle("missing_api_key")
